[package]
name = "echo"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
phlow-sdk = { workspace = true }

[dev-dependencies]
serde_json = "1.0"
phlow-runtime = { workspace = true }
phlow-engine = { workspace = true }

[lib]
name = "echo"
crate-type = ["cdylib"]
doctest = false
